services:
  backend:
    build: ./backend
    ports:
      - "8181:8181"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3300:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8181
    restart: unless-stopped
