services:
  backend:
    build: ./backend
    ports:
      - "8443:8443"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3300:80"
    environment:
      - REACT_APP_API_URL=https://localhost:8443
    restart: unless-stopped
